plugins {
    id 'net.fabricmc.fabric-loom' version '1.18-SNAPSHOT'
}
repositories { mavenCentral() }
dependencies {
    minecraft 'com.mojang:minecraft:26.3'
    implementation 'net.fabricmc:fabric-loader:0.19.5'
}
java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}
tasks.withType(JavaCompile).configureEach { options.release = 25 }
